### PR TITLE
Issue 1441 blockquerywait

### LINKED ISSUE #1441: Overriding block_query_wait Doesn't Work
### Consul Template version
consul-template v0.25.1 (b11fa800)

### Configuration

```hcl
block_query_wait = "333s"
max_stale = "88m"
log_level = "trace"
```

```liquid
No template
```

### Command

```shell
/usr/local/bin/consul-template -config /tmp/consul-template/conf.d/default.hcl
```

### Debug output
https://gist.github.com/orarnon/b4feb076ba8e1ca868ae63edc4289793

### Expected behavior

block_query_wait should be overwritten

### Actual behavior

block_query_wait is not overwritten

### Steps to reproduce

1. Use the above version and config file and watch for the block_query_wait value.

Consul-Template configuration in JSON format:
https://gist.github.com/orarnon/d04945a61386f187e848af91a73e68f9

### PR DESCRIPTION
**Pull request by eikenb**
Fix issue with block_query_wait setting.

Fixes #1441

### CODE REVIEW

**Review by findkim — APPROVED** [review]
I like how you added the test first. 👍

File: config/config.go [hunk 1]
```diff
@@ -222,9 +222,11 @@ func (c *Config) Merge(o *Config) *Config {
 		r.Wait = r.Wait.Merge(o.Wait)
 	}
 
-	r.Once = o.Once
+	if o.BlockQueryWaitTime != nil {
+		r.BlockQueryWaitTime = o.BlockQueryWaitTime
+	}
```
Comment (findkim) [inline config/config.go:227]: This check would probably be useful above in `Copy()` as well https://github.com/hashicorp/consul-template/blob/8ab9628fb643c435a77d1c8583674e0aff8fbc79/config/config.go#L152
